"""Add user accounts, email alerts, search analytics, and activity log tables

Revision ID: ea6d1be99847
Revises: add_property_pois
Create Date: 2026-01-14 10:05:35.497718

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ea6d1be99847'
down_revision = 'add_property_pois'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('email_alerts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('query', sa.String(length=500), nullable=True),
    sa.Column('filters', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('frequency', sa.String(length=20), nullable=False),
    sa.Column('notify_featured', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('verified', sa.Boolean(), nullable=False),
    sa.Column('verification_token', sa.String(length=100), nullable=True),
    sa.Column('last_sent_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('unsubscribe_token', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_email_alerts_email'), 'email_alerts', ['email'], unique=False)
    op.create_index(op.f('ix_email_alerts_is_active'), 'email_alerts', ['is_active'], unique=False)
    op.create_index(op.f('ix_email_alerts_unsubscribe_token'), 'email_alerts', ['unsubscribe_token'], unique=True)
    op.create_index(op.f('ix_email_alerts_verification_token'), 'email_alerts', ['verification_token'], unique=True)
    op.create_table('search_analytics',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('query', sa.String(length=500), nullable=True),
    sa.Column('filters', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('result_count', sa.Integer(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_search_analytics_created_at'), 'search_analytics', ['created_at'], unique=False)
    op.create_index(op.f('ix_search_analytics_query'), 'search_analytics', ['query'], unique=False)
    op.create_table('user_accounts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('verification_token', sa.String(length=100), nullable=True),
    sa.Column('locale', sa.String(length=10), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_accounts_email'), 'user_accounts', ['email'], unique=True)
    op.create_index(op.f('ix_user_accounts_verification_token'), 'user_accounts', ['verification_token'], unique=True)
    op.create_table('activity_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('activity_type', sa.Enum('PROPERTY_CREATED', 'PROPERTY_UPDATED', 'PROPERTY_DELETED', 'PROPERTY_PUBLISHED', 'PROPERTY_UNPUBLISHED', 'LOCATION_CREATED', 'LOCATION_UPDATED', 'LOCATION_DELETED', 'AGENT_CREATED', 'AGENT_UPDATED', 'AGENT_DELETED', 'LEAD_CREATED', 'LEAD_UPDATED', 'SETTINGS_UPDATED', 'USER_LOGIN', 'BULK_OPERATION', name='activitytype'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('user_email', sa.String(length=255), nullable=True),
    sa.Column('resource_type', sa.String(length=50), nullable=True),
    sa.Column('resource_id', sa.UUID(), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('changes', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_activity_logs_activity_type'), 'activity_logs', ['activity_type'], unique=False)
    op.create_index(op.f('ix_activity_logs_created_at'), 'activity_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_activity_logs_resource_id'), 'activity_logs', ['resource_id'], unique=False)
    op.create_index(op.f('ix_activity_logs_resource_type'), 'activity_logs', ['resource_type'], unique=False)
    op.create_index(op.f('ix_activity_logs_user_id'), 'activity_logs', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_activity_logs_user_id'), table_name='activity_logs')
    op.drop_index(op.f('ix_activity_logs_resource_type'), table_name='activity_logs')
    op.drop_index(op.f('ix_activity_logs_resource_id'), table_name='activity_logs')
    op.drop_index(op.f('ix_activity_logs_created_at'), table_name='activity_logs')
    op.drop_index(op.f('ix_activity_logs_activity_type'), table_name='activity_logs')
    op.drop_table('activity_logs')
    op.drop_index(op.f('ix_user_accounts_verification_token'), table_name='user_accounts')
    op.drop_index(op.f('ix_user_accounts_email'), table_name='user_accounts')
    op.drop_table('user_accounts')
    op.drop_index(op.f('ix_search_analytics_query'), table_name='search_analytics')
    op.drop_index(op.f('ix_search_analytics_created_at'), table_name='search_analytics')
    op.drop_table('search_analytics')
    op.drop_index(op.f('ix_email_alerts_verification_token'), table_name='email_alerts')
    op.drop_index(op.f('ix_email_alerts_unsubscribe_token'), table_name='email_alerts')
    op.drop_index(op.f('ix_email_alerts_is_active'), table_name='email_alerts')
    op.drop_index(op.f('ix_email_alerts_email'), table_name='email_alerts')
    op.drop_table('email_alerts')
    # ### end Alembic commands ###

