"""Initial schema

Revision ID: eb48d0dfd5e0
Revises: 
Create Date: 2026-01-08 03:17:12.379179

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eb48d0dfd5e0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=50), nullable=False),
    sa.Column('whatsapp', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('photo_key', sa.String(length=500), nullable=True),
    sa.Column('bio_en', sa.Text(), nullable=True),
    sa.Column('bio_ar', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('locations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name_en', sa.String(length=255), nullable=False),
    sa.Column('name_ar', sa.String(length=255), nullable=False),
    sa.Column('slug_en', sa.String(length=255), nullable=False),
    sa.Column('slug_ar', sa.String(length=255), nullable=False),
    sa.Column('parent_id', sa.UUID(), nullable=True),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lng', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['locations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_locations_slug_ar'), 'locations', ['slug_ar'], unique=True)
    op.create_index(op.f('ix_locations_slug_en'), 'locations', ['slug_en'], unique=True)
    op.create_table('settings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('site_name_en', sa.String(length=255), nullable=False),
    sa.Column('site_name_ar', sa.String(length=255), nullable=False),
    sa.Column('primary_color', sa.String(length=7), nullable=False),
    sa.Column('logo_key', sa.String(length=500), nullable=True),
    sa.Column('contact_phone', sa.String(length=50), nullable=True),
    sa.Column('contact_whatsapp', sa.String(length=50), nullable=True),
    sa.Column('facebook_url', sa.String(length=500), nullable=True),
    sa.Column('instagram_url', sa.String(length=500), nullable=True),
    sa.Column('meta_title_en', sa.String(length=255), nullable=True),
    sa.Column('meta_title_ar', sa.String(length=255), nullable=True),
    sa.Column('meta_desc_en', sa.Text(), nullable=True),
    sa.Column('meta_desc_ar', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('role', sa.Enum('admin', 'editor', name='userrole'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('properties',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title_en', sa.String(length=500), nullable=False),
    sa.Column('title_ar', sa.String(length=500), nullable=False),
    sa.Column('slug_en', sa.String(length=500), nullable=False),
    sa.Column('slug_ar', sa.String(length=500), nullable=False),
    sa.Column('description_en', sa.Text(), nullable=True),
    sa.Column('description_ar', sa.Text(), nullable=True),
    sa.Column('purpose', sa.Enum('sell', 'rent', name='propertypurpose'), nullable=False),
    sa.Column('type', sa.Enum('apartment', 'house', 'villa', 'land', 'commercial', 'office', 'store', name='propertytype'), nullable=False),
    sa.Column('status', sa.Enum('available', 'reserved', 'sold', 'rented', name='propertystatus'), nullable=False),
    sa.Column('price_amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('price_currency', sa.Enum('ILS', 'USD', 'JOD', name='propertycurrency'), nullable=False),
    sa.Column('area_m2', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('bedrooms', sa.Integer(), nullable=True),
    sa.Column('bathrooms', sa.Integer(), nullable=True),
    sa.Column('furnished', sa.Boolean(), nullable=False),
    sa.Column('parking', sa.Boolean(), nullable=False),
    sa.Column('floor', sa.Integer(), nullable=True),
    sa.Column('year_built', sa.Integer(), nullable=True),
    sa.Column('video_url', sa.String(length=500), nullable=True),
    sa.Column('lat', sa.Numeric(precision=10, scale=8), nullable=True),
    sa.Column('lng', sa.Numeric(precision=11, scale=8), nullable=True),
    sa.Column('show_exact_location', sa.Boolean(), nullable=False),
    sa.Column('featured', sa.Boolean(), nullable=False),
    sa.Column('published', sa.Boolean(), nullable=False),
    sa.Column('location_id', sa.UUID(), nullable=False),
    sa.Column('agent_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_properties_agent_id'), 'properties', ['agent_id'], unique=False)
    op.create_index(op.f('ix_properties_created_at'), 'properties', ['created_at'], unique=False)
    op.create_index(op.f('ix_properties_featured'), 'properties', ['featured'], unique=False)
    op.create_index(op.f('ix_properties_location_id'), 'properties', ['location_id'], unique=False)
    op.create_index(op.f('ix_properties_price_amount'), 'properties', ['price_amount'], unique=False)
    op.create_index(op.f('ix_properties_published'), 'properties', ['published'], unique=False)
    op.create_index(op.f('ix_properties_purpose'), 'properties', ['purpose'], unique=False)
    op.create_index(op.f('ix_properties_slug_ar'), 'properties', ['slug_ar'], unique=True)
    op.create_index(op.f('ix_properties_slug_en'), 'properties', ['slug_en'], unique=True)
    op.create_index(op.f('ix_properties_status'), 'properties', ['status'], unique=False)
    op.create_index(op.f('ix_properties_type'), 'properties', ['type'], unique=False)
    op.create_table('leads',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('property_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('new', 'contacted', 'closed', name='leadstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_leads_created_at'), 'leads', ['created_at'], unique=False)
    op.create_index(op.f('ix_leads_property_id'), 'leads', ['property_id'], unique=False)
    op.create_index(op.f('ix_leads_status'), 'leads', ['status'], unique=False)
    op.create_table('property_images',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('property_id', sa.UUID(), nullable=False),
    sa.Column('file_key', sa.String(length=500), nullable=False),
    sa.Column('alt_en', sa.String(length=500), nullable=True),
    sa.Column('alt_ar', sa.String(length=500), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_property_images_property_id'), 'property_images', ['property_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_property_images_property_id'), table_name='property_images')
    op.drop_table('property_images')
    op.drop_index(op.f('ix_leads_status'), table_name='leads')
    op.drop_index(op.f('ix_leads_property_id'), table_name='leads')
    op.drop_index(op.f('ix_leads_created_at'), table_name='leads')
    op.drop_table('leads')
    op.drop_index(op.f('ix_properties_type'), table_name='properties')
    op.drop_index(op.f('ix_properties_status'), table_name='properties')
    op.drop_index(op.f('ix_properties_slug_en'), table_name='properties')
    op.drop_index(op.f('ix_properties_slug_ar'), table_name='properties')
    op.drop_index(op.f('ix_properties_purpose'), table_name='properties')
    op.drop_index(op.f('ix_properties_published'), table_name='properties')
    op.drop_index(op.f('ix_properties_price_amount'), table_name='properties')
    op.drop_index(op.f('ix_properties_location_id'), table_name='properties')
    op.drop_index(op.f('ix_properties_featured'), table_name='properties')
    op.drop_index(op.f('ix_properties_created_at'), table_name='properties')
    op.drop_index(op.f('ix_properties_agent_id'), table_name='properties')
    op.drop_table('properties')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('settings')
    op.drop_index(op.f('ix_locations_slug_en'), table_name='locations')
    op.drop_index(op.f('ix_locations_slug_ar'), table_name='locations')
    op.drop_table('locations')
    op.drop_table('agents')
    # ### end Alembic commands ###

